### ISSUE TITLE
Having problems using

### ISSUE THREAD

**Issue by tmikaeld** [berstend/service-worker-router#2]
I get this error when importing or requiring the package:

`Module not found: Error: Can't resolve 'service-worker-router'`

If i load it manually as a file it loads, however, when I instantiate it i get this error from cloudflare API:

`"message": "Uncaught TypeError: n(...) is not a constructor\n  at line 1\n  at line 1 in n\n  at line 1\n  at line 1\n"`

I'm using Cloudflare workers.

**Comment by delta9** [comment]
Hey @berstend! First off: Great package, exactly what I was looking for to use with Cloudflare Workers.

Unfortunately, I'm having the same issue like @tmikaeld - not sure what's causing it to be honest.

As a workaround, I save and import the file* locally but it's not ideal.

*https://unpkg.com/service-worker-router

Thanks!

**Comment by tmikaeld** [comment]
@berstend I am using webpack, the rest of my project works just fine. Using several other packages including Typescript ones.

**Comment by berstend** [comment]
Thanks for the reports, I'll look into this tomorrow !

@tmikaeld If you could share your webpack config or example repo would be great, so I can quickly reproduce this issue

**Comment by berstend** [comment]
Or output from `webpack --display-error-details` would be great 😄

**Comment by delta9** [comment]
Hope this helps: https://gist.github.com/delta9/dc924eae83f3c0e2bd792e82b1fa412f

**Comment by berstend** [comment]
@delta9 @tmikaeld this issue should be fixed now in `service-worker-router@1.7.2`.

Apparently webpack got a little more sensitive about [relative imports](https://github.com/andreypopp/react-textarea-autosize/commit/866612508d248c592c3ffe4186306cff4c0c6af7) 😄
